- hosts: servers

  vars:
    nginx_port: 80
    root_dir: /etc/nginx
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      become: yes
      tags: nginx
    - name: copy html
      template:
        src: files/index.html
        dest: /usr/share/nginx/html/index.html
      notify:
        - restart nginx
      become: yes
    - name: update nginx config
      template:
        src: files/nginx.conf.j2
        dest: "{{root_dir}}/nginx.conf"
      notify:
        - restart nginx
      become: yes

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: reloaded
      become: yes
